---
title: "README"
output: 
  md_document:
    variant: markdown_github
---

##In this course we'll learn:

###Introduction to the R language
 
* vocabulary, syntax, data types, classes, etc;
* most used functions;
* built-in statistical tests;
* packages.

###Import, export and manipulation of data

* import and export data in common formats (\*.csv, \*.xls, \*.txt, …);
* tools for intuitive data manipulation (e.g., dplyr and tidyr).

###Visualization 

* introduction to the ggplot2 system of graphics.

###Transitioning from an R user to an R programmer

* how to make your own functions and custom tools to address questions related to your project;
* how to create packages to share code and data;
* introduction to version control with GitHub.

##General instructions

###To do before course begins

* Install R from [https://www.r-project.org](https://www.r-project.org)
* Install the Rstudio IDE from [Rstudio's website](https://www.rstudio.com/products/RStudio/#Desktop)
* Take the [TryR](http://tryr.codeschool.com) exercises

### Logistics:

Local: 
LIEG-UFES   

Dates: 
Nov 30 to Dec 4
9 - 12h and 14 - 16:30h 

##Bibliography

##### You can download the books below for free by choosing to "pay" $0 for them!

* [Peng R. R programming for Data Science. Leanpub, 2015](https://leanpub.com/rprogramming)
* [Peng R. Exploratory Data Analysis with R. Leanpub, 2015](https://leanpub.com/exdata)
